doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '10.4.28-MariaDB'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
