<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ3ZEGSH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ3ZEGSH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ3ZEGSH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ3ZEGSH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ3ZEGSH\App_KernelDevDebugContainer([
    'container.build_hash' => 'J3ZEGSH',
    'container.build_id' => '71359d8b',
    'container.build_time' => 1707570942,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ3ZEGSH');
