<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBAJ2tbY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBAJ2tbY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBAJ2tbY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBAJ2tbY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBAJ2tbY\App_KernelDevDebugContainer([
    'container.build_hash' => 'BAJ2tbY',
    'container.build_id' => '5a433c7a',
    'container.build_time' => 1708191891,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBAJ2tbY');
