<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYe4Eo1J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYe4Eo1J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYe4Eo1J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYe4Eo1J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYe4Eo1J\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ye4Eo1J',
    'container.build_id' => '19d9a621',
    'container.build_time' => 1707742384,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYe4Eo1J');
